name: Create & Publish Nuget Package
 
on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Setup nuget.exe
      uses: nuget/setup-nuget@v1
      
    - name: Build project
      run: msbuild.exe -p:configuration=release
    
    - name: Package project
      run: nuget.exe pack -prop configuration=release

    # If you want to publish your package to github, use below action
    - name: Publish to GitHub packages 
      run: dotnet nuget push nuget_package_name --api-key key_path --source github_packages_path --skip-duplicate