# This is workflow to check vulnerablities in your python source code. This Action is based on the Snyk CLI
name: Snyk for Python application
on:
  push:
    branches:
      - master  

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@master
      
      # Github action for running snyk to check vulnerabilities in your code
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }} # This is where you will need to introduce the Snyk API token created with your Snyk account